version: '3.8'

services:
  # 應用程式服務
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=todo_app
      - DB_URL=mysql://root:password@mysql:3306/todo_app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - mysql
    command: >
      sh -c "npm run migrate && node ."
    restart: unless-stopped
    networks:
      - todo-app-network

  # MySQL 資料庫服務
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_app
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - todo-app-network

  # Adminer 資料庫管理工具（取代 phpMyAdmin，更好支援 ARM 架構）
  adminer:
    image: adminer:latest
    container_name: todo-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - todo-app-network

volumes:
  mysql-data:
    driver: local

networks:
  todo-app-network:
    driver: bridge
